[package]
name = "parson"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.96"
anyhow = "1.0.71"
crossterm = "0.25"
flate2 = "1.0.34"
ratatui = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
