# Parson Configuration File

[general]
name = "parson"
version = "0.1.0"

[folders]
# Specify the input folder path
input_folder = "/workspaces/rust/JSIN"

[performance]
# Default compression level for file compression (1-9, where 9 is highest)
default_compression_level = 6

[formatting]
# Default number of spaces for indentation in pretty printing
default_indent_spaces = 2

# Maximum file size (in MB) for processing
max_file_size = 100

# Note: Adjust these settings as needed for your specific deployment environment
